### ISSUE TITLE
Лагающий Synedit

### ISSUE THREAD

**Issue by ghost** [dim-s/soulengine#7]
К исходникам  не прилогается требуемый пакет Synedit, последняя версия - несовместима, т.к там событие OnKeyPress изменено на OnKeyPressW, а проверить наполнение SynCompletetionProposal невозможно, ведь содержимое наполняется единожды и далее не очищается.
Чтобы очистить содержимое, нужно показать SCP, уже потом можно проверять, не иначе.
Да, баг со стороны Synapse Team, но однако, можно узнать какая версия требуется?
В прилогаемой версии же баг с Ansi - в студии отображается некорректно, некоторые свойства, так, сказать 'Glitchy'.

**Comment by Kashaket** [comment]
Upd. Редактирование кода компонента помогло.

**Comment by ghost** [comment]
Upd. Редактирование кода компонента помогло.
